config/routes.rb
Rails.application.routes.draw do
  resources :perks
  
  devise_for :users
  root	"pages#home"
  get "about" => "pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/perk.rb
class Perk < ApplicationRecord
	belongs_to :user

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
	has_attached_file :partnerlogo, styles: { medium: "300x300>", thumb: "100x100>" }
	has_attached_file :smallimage, styles: { medium: "300x300>", thumb: "100x100>" }
	validates_attachment_content_type :image, :partnerlogo, :smallimage, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :perks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/perks_controller.rb
class PerksController < ApplicationController
  before_action :set_perk, only: [:show, :edit, :update, :destroy]
  #before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  before_action :verify_is_admin, except: [:index, :show]

  def index
    @perks = Perk.all
  end

  def show
  end

  def new
    @perk = current_user.perks.build
  end

  def edit
  end

  def create
    @perk = current_user.perks.build(perk_params)
    if @perk.save
      redirect_to @perk, notice: 'Perk was successfully created.' 
    else
      render action: "new"
    end
  end

  def update
    if @perk.update(perk_params)
      redirect_to @perk, notice: 'Perk was successfully updated.' 
    else
      render action: "edit"
    end
  end

  def destroy
    @perk.destroy
    redirect_to perks_url, notice: 'Perk was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perk
      @perk = Perk.find(params[:id])
    end

    def verify_is_admin
     (current_user.nil?) ? redirect_to(@perk) : (redirect_to(@perk) unless current_user.admin?)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perk_params
      params.require(:perk).permit(:description, :image, :smallimage, :partnerlogo, :partner_name, :offer_title, :partner_description, :partner_website, :partner_area, :perk_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/perks_helper.rb
module PerksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Workeers", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "À propos", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Catalogue", perks_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-outline-dark" %>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "btn btn-danger" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workeers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container"> 
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>À propos de Workeers</h1>

<p>Workeers est un plateforme où vos employés ont accès à des dizaines d'offres uniques négociées par nos équipes en direct avec des marques des secteurs de la mode, du tourisme, du sport, de la gastronomie et bien d'autres.</p>

app/views/pages/home.html.erb
<div class="center">
	<h1>Welcome on Workeers</h1>
	<% if user_signed_in? %>
		<%= link_to 'Accéder au catalogue', perks_path, class: "btn btn-primary" %>
	<% else %>
		<p>Please <%= link_to "Log in", new_user_session_path, class: "btn btn-danger" %> or <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-dark" %></p>
	<% end %>
</div>

app/views/perks/_form.html.erb
<%= form_with model: perk, local: true, html: { multipart: true } do |form| %>
  <% if perk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(perk.errors.count, "error") %> prohibited this perk from being saved:</h2>

      <ul>
      <% perk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= form.label :partner_name %>
    <%= form.text_field :partner_name, id: :partner_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :partnerlogo %>
    <%= form.file_field :partnerlogo, id: :partnerlogo, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :offer_title %>
    <%= form.text_field :offer_title, id: :offer_title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :partner_description %>
    <%= form.text_field :partner_description, id: :partner_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :partner_website %>
    <%= form.text_field :partner_website, id: :partner_website, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label :partner_area %>
    <%= form.text_field :partner_area, id: :partner_area, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :perk_code %>
    <%= form.text_field :perk_code, id: :perk_code, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, id: :perk_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :smallimage %>
    <%= form.file_field :smallimage, id: :perk_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, id: :perk_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-danger" %>
  </div>
<% end %>

app/views/perks/edit.html.erb
<h1>Editing Perk</h1>

<%= render 'form', perk: @perk %>

<%= link_to 'Show', @perk %> |
<%= link_to 'Back', perks_path %>

app/views/perks/index.html.erb
<% if current_user.try(:admin?) %>
  <h1>Ajout d'un nouveau perk</h1>
  <br>
  <%= link_to raw('<i class="fa fa-plus" aria-hidden="true"></i> New Perk'), new_perk_path, class: "btn btn-danger" %>
  <br>
  <br>
  <hr>
<% end %>

<h1 class="mb-5">Catalogue d'offres</h1>

<div class="row">
  <% @perks.each do |perk| %>
    <div class="col-md-4">
      <div class="card">
        <%= link_to image_tag(perk.smallimage.url), perk, class: "card-img-top" %>
        <div class="card-body">
          <h5 class="card-title"><%= perk.offer_title %></h5>

          <div class="action">
            <%= link_to 'Accéder', perk, class: "btn btn-primary" %>
            <% if current_user.try(:admin?) %>
              <%= link_to 'Edit', edit_perk_path(perk), class: "btn btn-warning" %>
              <%= link_to 'Destroy', perk, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/perks/new.html.erb
<h1>New Perk</h1>

<%= render 'form', perk: @perk %>

<%= link_to 'Back', perks_path %>

app/views/perks/show.html.erb
<%= link_to 'Retour au catalogue', perks_path %>
<%= image_tag @perk.image.url, class: "img-fluid" %>
<h2><%= @perk.partner_name %> | <%= @perk.offer_title %></h2>
<hr>
<div class="row">
	<div class="col-md-6">
		<h3>Description Partenaire</h3>
		<p><%= @perk.partner_description %></p>
		<br>
		<h3>Site internet</h3>
		<p><%= @perk.partner_website %></p>
		<br>
		<h3>Zone d'utilisation</h3>
		<p><%= @perk.partner_area %></p>
	</div>
	<div class="col-md-6">
		<h3>Description de l'offre</h3>
		<p><%= @perk.description %></p>
		<br>
		<h3>Offre</h3>
		<p>
			<% if user_signed_in? %>	
				<%= @perk.perk_code %>
			<% else %>
				Inscrivez-vous pour connaitre le code
			<% end %>
		</p>
		<br>
		<h3>Logo Partenaire</h3>
		<%= image_tag @perk.partnerlogo.url, class: "img-thumbnail" %>
	</div>

  <% if current_user.try(:admin?) %>
    <%= link_to 'Edit', edit_perk_path(@perk), class: "btn btn-warning" %>
    <%= link_to 'Destroy', @perk, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  <% end %>
		    
</div>